### ISSUE TITLE
So basically there was a connection error...?

### ISSUE THREAD

**Issue by sniperstyx** [DevDenisYT/YouTubeMusicDiscordRichPresence#2]
So basically I tried to open it and apparently I am getting that error. I don't know how to fix it. I did all the steps correctly.

![image](https://user-images.githubusercontent.com/52759847/112672342-47a38900-8e5b-11eb-88ce-2c766337e871.png)

**Comment by Alpakat** [comment]
You have to set up an Application at [https://discord.com/developers](https://discord.com/developers).
Then Copy the APPLICATION ID to the top of the code
`const client = require('discord-rich-presence')('YOUR ID HERE')`

And add the Images to "Rich Presence"

After I did this, it worked for me.

**Comment by isayakmondal** [comment]
Hey could you explain more elaborately what do you mean by 

> "And add the Images to "Rich Presence"

And also does the pause feature work for you or is it not present in the application?
@Alpakat
